/**
 * Creates a package link
 */

module.exports = (root, child, isSubDependency) => {
	return `--[[
	Package link auto-generated by Kayak
]]

local PackageIndex = ${isSubDependency ? "script.Parent.Parent" : "script.Parent._index"}

local package = PackageIndex["${root}"]["${child}"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package`
}
