/**
 * Creates a package link
 */

module.exports = (root, child) => {
	return `--[[
	Package link auto-generated by Kayak
]]

local PackageIndex = script.Parent._index

local package = PackageIndex["${root}"]["${child}"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package`
}
